"""Initial schema

Revision ID: 13a9cdf59706
Revises: 
Create Date: 2026-08-30 19:10:07.391396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a9cdf59706'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_logs',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('audit_timestamp', sa.String(length=64), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('issue_category', sa.String(length=128), nullable=False),
    sa.Column('severity', sa.String(length=32), nullable=False),
    sa.Column('affected_record_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_logs_audit_timestamp'), 'data_quality_logs', ['audit_timestamp'], unique=False)
    op.create_index(op.f('ix_data_quality_logs_issue_category'), 'data_quality_logs', ['issue_category'], unique=False)
    op.create_index(op.f('ix_data_quality_logs_severity'), 'data_quality_logs', ['severity'], unique=False)
    op.create_table('facilities',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('facility_code', sa.String(length=64), nullable=True),
    sa.Column('facility_name', sa.String(length=255), nullable=False),
    sa.Column('facility_type', sa.String(length=64), nullable=False),
    sa.Column('state', sa.String(length=128), nullable=False),
    sa.Column('district', sa.String(length=128), nullable=False),
    sa.Column('sub_district', sa.String(length=128), nullable=True),
    sa.Column('raw_facility_name', sa.String(length=255), nullable=False),
    sa.Column('raw_district_name', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_facility_state_district', 'facilities', ['state', 'district'], unique=False)
    op.create_index(op.f('ix_facilities_district'), 'facilities', ['district'], unique=False)
    op.create_index(op.f('ix_facilities_facility_code'), 'facilities', ['facility_code'], unique=True)
    op.create_index(op.f('ix_facilities_facility_type'), 'facilities', ['facility_type'], unique=False)
    op.create_index(op.f('ix_facilities_state'), 'facilities', ['state'], unique=False)
    op.create_table('indicators',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=128), nullable=False),
    sa.Column('unit', sa.String(length=64), nullable=False),
    sa.Column('source_system', sa.String(length=64), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_indicators_category'), 'indicators', ['category'], unique=False)
    op.create_index(op.f('ix_indicators_code'), 'indicators', ['code'], unique=True)
    op.create_table('model_metadata',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=64), nullable=False),
    sa.Column('target_indicator', sa.String(length=64), nullable=False),
    sa.Column('training_start', sa.String(length=10), nullable=False),
    sa.Column('training_end', sa.String(length=10), nullable=False),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('mae', sa.Float(), nullable=True),
    sa.Column('rmse', sa.Float(), nullable=True),
    sa.Column('mape', sa.Float(), nullable=True),
    sa.Column('baseline_mae', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metadata_model_version'), 'model_metadata', ['model_version'], unique=False)
    op.create_index(op.f('ix_model_metadata_target_indicator'), 'model_metadata', ['target_indicator'], unique=False)
    op.create_table('forecasts',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('indicator_id', sa.String(length=64), nullable=False),
    sa.Column('forecast_date', sa.String(length=10), nullable=False),
    sa.Column('predicted_value', sa.Float(), nullable=False),
    sa.Column('lower_bound', sa.Float(), nullable=True),
    sa.Column('upper_bound', sa.Float(), nullable=True),
    sa.Column('model_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_forecast_fac_ind_date', 'forecasts', ['facility_id', 'indicator_id', 'forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_facility_id'), 'forecasts', ['facility_id'], unique=False)
    op.create_index(op.f('ix_forecasts_forecast_date'), 'forecasts', ['forecast_date'], unique=False)
    op.create_index(op.f('ix_forecasts_indicator_id'), 'forecasts', ['indicator_id'], unique=False)
    op.create_table('observations',
    sa.Column('id', sa.String(length=128), nullable=False),
    sa.Column('facility_id', sa.String(length=64), nullable=False),
    sa.Column('indicator_id', sa.String(length=64), nullable=False),
    sa.Column('observation_date', sa.String(length=10), nullable=False),
    sa.Column('reporting_month', sa.String(length=7), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_type', sa.String(length=32), nullable=False),
    sa.Column('validation_status', sa.String(length=32), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=False),
    sa.Column('source_sheet', sa.String(length=128), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('ingested_at', sa.String(length=64), nullable=False),
    sa.Column('transformation_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['facility_id'], ['facilities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['indicator_id'], ['indicators.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('facility_id', 'indicator_id', 'observation_date', name='uq_facility_indicator_date')
    )
    op.create_index('idx_obs_fac_ind_date', 'observations', ['facility_id', 'indicator_id', 'observation_date'], unique=False)
    op.create_index(op.f('ix_observations_facility_id'), 'observations', ['facility_id'], unique=False)
    op.create_index(op.f('ix_observations_indicator_id'), 'observations', ['indicator_id'], unique=False)
    op.create_index(op.f('ix_observations_observation_date'), 'observations', ['observation_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_observations_observation_date'), table_name='observations')
    op.drop_index(op.f('ix_observations_indicator_id'), table_name='observations')
    op.drop_index(op.f('ix_observations_facility_id'), table_name='observations')
    op.drop_index('idx_obs_fac_ind_date', table_name='observations')
    op.drop_table('observations')
    op.drop_index(op.f('ix_forecasts_indicator_id'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_forecast_date'), table_name='forecasts')
    op.drop_index(op.f('ix_forecasts_facility_id'), table_name='forecasts')
    op.drop_index('idx_forecast_fac_ind_date', table_name='forecasts')
    op.drop_table('forecasts')
    op.drop_index(op.f('ix_model_metadata_target_indicator'), table_name='model_metadata')
    op.drop_index(op.f('ix_model_metadata_model_version'), table_name='model_metadata')
    op.drop_table('model_metadata')
    op.drop_index(op.f('ix_indicators_code'), table_name='indicators')
    op.drop_index(op.f('ix_indicators_category'), table_name='indicators')
    op.drop_table('indicators')
    op.drop_index(op.f('ix_facilities_state'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_type'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_facility_code'), table_name='facilities')
    op.drop_index(op.f('ix_facilities_district'), table_name='facilities')
    op.drop_index('idx_facility_state_district', table_name='facilities')
    op.drop_table('facilities')
    op.drop_index(op.f('ix_data_quality_logs_severity'), table_name='data_quality_logs')
    op.drop_index(op.f('ix_data_quality_logs_issue_category'), table_name='data_quality_logs')
    op.drop_index(op.f('ix_data_quality_logs_audit_timestamp'), table_name='data_quality_logs')
    op.drop_table('data_quality_logs')
    # ### end Alembic commands ###
